 # Setting up Postgresql Database
  default: &default
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: localhost
    port: 5432

  development:
    <<: *default
    database: todo_development
    username: pguser
    password: password

  test:
    <<: *default
    database: todo_test
    username: pguser
    password: password
